In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('bolig_data.csv')

In [13]:
df['monthly_aconto'] = df['monthly_aconto'].apply(lambda x: x.replace('kr', '').replace('.', '').replace(',', '').strip() if x else '0').astype(float)

In [14]:
df.drop(index=df[df['monthly_aconto']>3131.16].index,inplace=True)

In [15]:
df['monthly_aconto'] = df['monthly_aconto'].astype(int).astype(str).apply(lambda x: x+' kr.')

In [16]:
df

,breadcrumb,title,description,address,monthly_rent,monthly_aconto,move_in_price,available_from,rental_period,Boligtype,...,Ledig fra,Månedlig leje,Aconto,Depositum,Forudbetalt husleje,Indflytningspris,Oprettelsesdato,Sagsnr.,energy_mark_src,Energimærke
0,Hjem > Lejligheder > København > 3 værelses > ...,"Furnished apartment, 2 bedroom",Fully furnished charming apartment for rent in...,"3 timer siden, Erik Menveds Vej, 1965 Københav...",12.850 kr.,1350 kr.,52.750 kr.,Snarest muligt,52.750 kr.,Lejlighed,...,Snarest muligt,12.850 kr.,1.350 kr.,38.550 kr.,0 kr.,52.750 kr.,7.9.2024,5080588,/static/images/energy_labels/D_str2.png,NaN
1,Hjem > Lejligheder > København > 4 værelses > ...,Velindrettet 4-værelses lejlighed på 113 m2 me...,Indretning:\n\nVelkommen indefor i denne store...,"9 timer siden, Laurentsvej, 2880 København, Ba...",15.700 kr.,1224 kr.,79.724 kr.,15. november 2024,79.724 kr.,Lejlighed,...,15. november 2024,15.700 kr.,1.224 kr.,47.100 kr.,15.700 kr.,79.724 kr.,7.9.2024,5455654,/static/images/energy_labels/A15_str2.png,NaN
2,Hjem > Værelser > København > 1 værelses > Kas...,Brand new room for rent in newly build house,9m2 værelse i nybygget hus til leje \n(kan lej...,"11 timer siden, Pilegård Alle, 2770 København,...",5.000 kr.,1000 kr.,21.000 kr.,1. december 2024,21.000 kr.,Værelse,...,1. december 2024,5.000 kr.,1.000 kr.,15.000 kr.,0 kr.,21.000 kr.,7.9.2024,5455638,/static/images/energy_labels/A20_str2.png,NaN
3,Hjem > Værelser > København > 1 værelses > Køb...,Værelse i Villa ved strand og Metro,Et værelse udlejes i en skøn villa i et dejlig...,"11 timer siden, Borneovej, 2300 København, Køb...",3.500 kr.,500 kr.,11.500 kr.,1. november 2024,11.500 kr.,Værelse,...,1. november 2024,3.500 kr.,500 kr.,4.000 kr.,3.500 kr.,11.500 kr.,7.9.2024,5144039,/static/images/energy_labels/C_str2.png,NaN
4,Hjem > Værelser > København > 1 værelses > Køb...,Small Single Room,Hi there!\n\nAre you going to study in Copenha...,"13 timer siden, Vesterbrogade, 1620 København,...",4.650 kr.,0 kr.,13.950 kr.,Snarest muligt,13.950 kr.,Værelse,...,Snarest muligt,4.650 kr.,0 kr.,9.300 kr.,0 kr.,13.950 kr.,7.9.2024,5455643,none,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1892,Hjem > Lejligheder > København > 1 værelses > ...,"Nyt lejlighedshotel i Nærum, Rundforbivej - St...",Bo inkl. alt forbrug (minimum 2 måneder) - f.e...,"21. april, Rundforbivej, 2850 København, Nærum",16.900 kr.,0 kr.,33.800 kr.,Snarest muligt,33.800 kr.,Lejlighed,...,Snarest muligt,16.900 kr.,0 kr.,16.900 kr.,0 kr.,33.800 kr.,21.4.2022,4631928,none,-
1893,Hjem > Lejligheder > København > 4 værelses > ...,4 værelses lejlighed på Hyrdindestien i Herlev...,Området består af tre bebyggelser i forskellig...,"16. februar, Hyrdindestien, 2730 København, He...",14.595 kr.,950 kr.,73.925 kr.,Snarest muligt,73.925 kr.,Lejlighed,...,Snarest muligt,14.595 kr.,950 kr.,43.785 kr.,14.595 kr.,73.925 kr.,16.2.2022,5143389,none,-
1894,Hjem > Værelser > København > 1 værelses > Køb...,Stille værelse tæt på station og UN city,Jeg udlejer et møbleret værelse.\nDu får adgan...,"17. juli, Marstalsgade, 2100 København, Københ...",8.000 kr.,0 kr.,18.000 kr.,Snarest muligt,18.000 kr.,Værelse,...,Snarest muligt,8.000 kr.,0 kr.,10.000 kr.,0 kr.,18.000 kr.,17.7.2021,5091127,none,-
1895,Hjem > Lejligheder > København > 3 værelses > ...,High end penthouse apartment in the heart of C...,Exclusive luxury penthouse apartment in the he...,"7. juli, Arkonagade, 1726 København, København...",28.000 kr.,0 kr.,38.000 kr.,1. oktober 2024,38.000 kr.,Lejlighed,...,1. oktober 2024,28.000 kr.,0 kr.,10.000 kr.,0 kr.,38.000 kr.,7.7.2021,5204260,/static/images/energy_labels/A20_str2.png,NaN
1896,Hjem > Værelser > København > 1 værelses > Køb...,Værelse til leje,Østerbro 1 værelse møbleret på 22 kvm herskabs...,"29. oktober, Jagtvej, 2100 København, Københav...",3.800 kr.,0 kr.,15.200 kr.,Snarest muligt,15.200 kr.,Værelse,...,Snarest muligt,3.800 kr.,0 kr.,7.600 kr.,3.800 kr.,15.200 kr.,29.10.2020,5024726,none,-

In [17]:
df.to_csv('bolig_data1.csv')